---
sidebar: sidebar 
permalink: reference-private-data-categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Cloud Data Sense可在您的磁碟區、Amazon S3儲存區、資料庫、OneDrive資料夾、SharePoint帳戶、 和Google雲端硬碟帳戶。 
---
= 私有資料類別
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Data Sense可在您的磁碟區、Amazon S3儲存區、資料庫、OneDrive資料夾、SharePoint帳戶、 和Google雲端硬碟帳戶。請參閱下列類別。


TIP: 如果您需要Cloud Data Sense來識別其他私有資料類型、例如其他國家ID號碼或醫療識別碼、請寄送電子郵件至ng-contact-data-sense@netapp.com並附上您的要求。



== 個人資料類型

檔案中的個人資料可以是一般個人資料或國家識別碼。第三欄會識別Cloud Data Sense是否使用 link:task-controlling-private-data.html#viewing-files-that-contain-personal-data["鄰近驗證"^] 驗證識別碼的發現。

此類別中的項目可以任何語言辨識。

請注意、如果您正在掃描資料庫伺服器、可以新增至檔案中的個人資料清單。Data Fusion SURE_功能可讓您在資料庫表格中選取欄位、以選擇Cloud Data Sense在掃描中所要尋找的其他識別碼。請參閱 link:task-managing-data-fusion.html["使用 Data Fusion 功能新增個人資料識別碼"^] 以取得詳細資料。

[cols="20,50,18"]
|===
| 類型 | 識別碼 | 鄰近驗證？ 


.5+| 一般 | 電子郵件地址 | 否 


| 信用卡號碼 | 否 


| IBAN 編號（國際銀行帳戶號碼） | 否 


| IP 位址 | 否 


| 密碼 | 是的 


.42+| 國家識別碼 | 澳洲（TFN）（稅務檔案編號） | 是的 


| 澳洲駕駛人授權號碼 | 是的 


| 澳洲醫療保險號碼 | 是的 


| 澳洲護照號碼 | 是的 


| 奧地利SSN | 是的 


| 比利時 ID （ Numero National ） | 是的 


| 巴西 ID （ CPF ） | 是的 


| 英國護照 | 是的 


| 保加利亞文 ID （ UCN） | 是的 


| California Driver's License （加州駕駛授權） | 是的 


| 克羅地亞 ID （ OIB ） | 是的 


| 塞浦路斯稅務識別編號（ TIC ） | 是的 


| 捷克文 / 斯洛伐克文 ID | 是的 


| 丹麥文 ID （ CPR） | 是的 


| 荷蘭文 ID （ BSN ） | 是的 


| 愛沙尼亞 ID | 是的 


| 芬蘭文 ID （ HETU ） | 是的 


| 法文驅動程式授權 | 是的 


| 法文ID | 是的 


| 法國INSEE | 是的 


| 法國社會安全號碼 | 是的 


| 法文稅務識別編號（ SPI ） | 是的 


| 德國稅務識別編號（ Steuerlice 識別碼） | 是的 


| 希臘文 ID | 是的 


| 匈牙利稅務識別編號 | 是的 


| 愛爾蘭 ID （ PPS ） | 是的 


| 以色列 ID | 是的 


| 義大利稅務識別編號 | 是的 


| 拉脫維亞 ID | 是的 


| 立陶宛 ID | 是的 


| 盧森堡 ID | 是的 


| 馬爾他 ID | 是的 


| 國家醫療服務（NHS）編號 | 是的 


| 波蘭文 ID （ PESEL ） | 是的 


| 葡萄牙稅務識別號碼（ NIF ） | 是的 


| 羅馬尼亞 ID （ CNP ） | 是的 


| 斯洛維尼亞 ID （ EMSO ） | 是的 


| 南非 ID | 是的 


| 西班牙稅務識別編號 | 是的 


| 瑞典文 ID | 是的 


| 英國ID （ Nino ） | 是的 


| 美國社會安全號碼（ SSN ） | 是的 
|===


== 敏感個人資料的類型

Cloud Data Sense可在檔案中找到的敏感個人資料包括下列清單。此類別中的項目目前只能以英文辨識。

刑事訴訟程序參考資料:: 關於任何人的刑事定罪和犯罪的資料。
族群參考資料:: 關於一個人的種族或族裔來源的資料。
健全狀況參考資料:: 關於自然人健康的資料。
ICD-9-CM 醫療代碼:: 醫療與醫療產業所使用的代碼。
ICD-10-CM 醫療代碼:: 醫療與醫療產業所使用的代碼。
哲學理念參考資料:: 關於自然人哲學理念的資料。
政治意見參考資料:: 關於天然人物政治見解的資料。
《宗教信仰參考》:: 關於自然人的宗教信仰的資料。
性生活或取向參考資料:: 關於自然人性生活或性取向的資料。




== 類別類型

Cloud Data Sense會將您的資料分類如下。這些類別大部分都能以英文、德文和西班牙文辨識。

[cols="25,25,15,15,15"]
|===
| 類別 | 類型 | 英文 | 德文 | 西班牙文 


.4+| 財務 | 平衡表 | ✓ | ✓ | ✓ 


| 訂單 | ✓ | ✓ | ✓ 


| 發票 | ✓ | ✓ | ✓ 


| 季度報告 | ✓ | ✓ | ✓ 


.6+| 人力資源 | 背景檢查 | ✓ |  | ✓ 


| 補償計畫 | ✓ | ✓ | ✓ 


| 員工合約 | ✓ |  | ✓ 


| 員工審查 | ✓ |  | ✓ 


| 健全狀況 | ✓ |  | ✓ 


| 恢復 | ✓ | ✓ | ✓ 


.2+| 合法 | NDAs | ✓ | ✓ | ✓ 


| 廠商 - 客戶合約 | ✓ | ✓ | ✓ 


.2+| 行銷 | 行銷活動 | ✓ | ✓ | ✓ 


| 會議 | ✓ | ✓ | ✓ 


| 營運 | 稽核報告 | ✓ | ✓ | ✓ 


| 銷售 | 銷售訂單 | ✓ | ✓ |  


.4+| 服務 | RFI | ✓ |  | ✓ 


| RFP | ✓ |  | ✓ 


| SOW | ✓ | ✓ | ✓ 


| 訓練 | ✓ | ✓ | ✓ 


| 支援 | 投訴與門票 | ✓ | ✓ | ✓ 
|===
下列中繼資料也會分類、並以相同的支援語言識別：

* 應用程式資料
* 歸檔檔案
* 音訊
* 商業應用程式資料
* CAD 檔案
* 程式碼
* 毀損
* 資料庫與索引檔案
* 設計檔案
* 電子郵件應用程式資料
* 加密
* 可執行檔
* 財務應用程式資料
* 健全狀況應用程式資料
* 映像
* 記錄
* 雜項文件
* 其他簡報
* 其他試算表
* 其他「未知」
* 結構化資料
* 影片
* 零位元組檔案




== 檔案類型

Cloud Data Sense會掃描所有檔案以取得類別和中繼資料深入資訊、並在儀表板的「檔案類型」區段中顯示所有檔案類型。

但當Data Sense偵測到個人識別資訊（PII）、或執行DSAR搜尋時、僅支援下列檔案格式：

.CSV、.dcm、.dicom、.dDOC、.DOCX、 .Json、.PDF、.PPTX、.RTF、.TXT、 .XLS、.XLSX、文件、工作表及Slides +



== 找到資訊的準確度

NetApp無法保證Cloud Data有意義的個人資料和敏感個人資料100%準確無誤。您應該一律檢閱資料來驗證資訊。

根據我們的測試結果、下表顯示Data Sense發現的資訊準確度。我們將其細分為 _精密度 _ 和 _Recall _ ：

精確性:: 已正確識別出Data Sense發現的可能性。例如、 90% 的個人資料精準率表示、在 10 個被識別為包含個人資訊的檔案中、有 9 個檔案實際上包含個人資訊。10 個檔案中有 1 個是誤報的。
回收:: 「資料感測」找到應有的可能性。例如、70%的個人資料回收率表示Data Sense可識別出組織中實際包含個人資訊的10個檔案中的7個。Data Sense會遺漏30%的資料、而且不會出現在儀表板中。


我們不斷改善結果的準確度。這些改良功能將會在未來的Data Sense版本中自動提供。

[cols="25,20,20"]
|===
| 類型 | 精確性 | 回收 


| 個人資料 - 一般 | 90% 至 95% | 60% 至 80% 


| 個人資料 - 國家 / 地區識別碼 | 30% 至 60% | 40% 至 60% 


| 敏感的個人資料 | 80% 至 95% | 20% 至 30% 


| 類別 | 90% 至 97% | 60% 至 80% 
|===